// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name, price_in_center, quantity
) VALUES (
  $1, $2, $3
)
RETURNING id, name, price_in_center, quantity, created_at
`

type CreateProductParams struct {
	Name          string `json:"name"`
	PriceInCenter int32  `json:"price_in_center"`
	Quantity      int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceInCenter, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenter,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT 
  id, name, price_in_center, quantity, created_at 
FROM 
  products 
WHERE 
  id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenter,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT 
  id, name, price_in_center, quantity, created_at
FROM
  products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCenter,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
